import { db } from "../../db";

const users = [
  {
    id: "db0445b7-0a4d-4f6d-97ef-139a00eacd51",
    name: "Rakel Patis",
    password: "Y36RzH2",
    email: "rpatis0@sbwire.com",
    role: "MEMBER",
    bio: "e-enable cross-platform e-services",
    avatar: "https://robohash.org/doloresrerumrepudiandae.png?size=110x110&set=set1",
  },
  {
    id: "d38b453c-5157-452b-8247-ae588011ce6d",
    name: "Yvor Filliskirk",
    password: "8Cl1I0",
    email: "yfilliskirk1@webeden.co.uk",
    role: "MEMBER",
    bio: "drive customized partnerships",
    avatar: "https://robohash.org/impeditundesint.png?size=110x110&set=set1",
  },
  {
    id: "47891b34-4253-4ae0-90bb-9c5822b60597",
    name: "Norton Ruffle",
    password: "4MfUa0GL",
    email: "nruffle2@ameblo.jp",
    role: "STAFF",
    bio: "visualize open-source e-services",
    facebook: "https://amazon.com",
    instagram: "https://zdnet.com",
    twitter: "http://state.gov",
    linkedin: "https://php.net",
    avatar: "https://robohash.org/nonutomnis.png?size=110x110&set=set1",
  },
  {
    id: "8e411eaf-edee-4bf2-b1cd-41b6d086b24f",
    name: "Ellary Ricketts",
    password: "uJKz2XNP6",
    email: "ericketts3@ocn.ne.jp",
    role: "MEMBER",
    bio: "unleash wireless infomediaries",
    avatar: "https://robohash.org/dolorumaliquidet.png?size=110x110&set=set1",
  },
  {
    id: "341a4ca9-fbb2-4ca8-be1e-48e8643d1944",
    name: "Zaria Sampey",
    password: "MIdaugVuqq9",
    email: "zsampey4@uiuc.edu",
    role: "ADMIN",
    bio: "extend integrated communities",
    facebook: "https://telegraph.co.uk",
    instagram: "http://weather.com",
    twitter: "https://samsung.com",
    linkedin: "http://xing.com",
    avatar: "https://robohash.org/possimusconsequunturitaque.png?size=110x110&set=set1",
  },
  {
    id: "d5f6b39c-0542-4c2c-91f3-d24939d1d5ed",
    name: "Susette Glowacki",
    password: "mNdnWAB",
    email: "sglowacki5@salon.com",
    role: "STAFF",
    bio: "strategize synergistic content",
    avatar: "https://robohash.org/fugaestaut.png?size=110x110&set=set1",
  },
  {
    id: "2727d3ee-5e42-407e-b559-a5529df8af37",
    name: "Aldric Driver",
    password: "3cTQ2ik",
    email: "adriver6@boston.com",
    role: "MEMBER",
    bio: "whiteboard ubiquitous architectures",
    avatar: "https://robohash.org/odionesciuntmagnam.png?size=110x110&set=set1",
  },
  {
    id: "ef831fe2-3942-4db2-a2bc-cab04fa4958d",
    name: "Yolande Orrick",
    password: "v1ViFB",
    email: "yorrick7@who.int",
    role: "MEMBER",
    bio: "e-enable intuitive infrastructures",
    avatar: "https://robohash.org/estetet.png?size=110x110&set=set1",
  },
  {
    id: "2c6bb6b6-b79c-4e82-9ab1-530bde4840ae",
    name: "Buddy Naris",
    password: "8RA8sUL",
    email: "bnaris8@psu.edu",
    role: "MEMBER",
    bio: "engage interactive experiences",
    facebook: "http://princeton.edu",
    instagram: "https://vinaora.com",
    twitter: "https://wisc.edu",
    linkedin: "http://ustream.tv",
    avatar: "https://robohash.org/rerumaccusamusnostrum.png?size=110x110&set=set1",
  },
  {
    id: "c11598b0-5ecd-4b27-b643-c2d460894852",
    name: "Nickey Giorio",
    password: "b9MKbUNCKyf",
    email: "ngiorio9@wikipedia.org",
    role: "STAFF",
    bio: "synthesize collaborative action-items",
    facebook: "http://mapy.cz",
    instagram: "https://google.com.hk",
    twitter: "http://fda.gov",
    linkedin: "http://instagram.com",
    avatar: "https://robohash.org/eumeossint.png?size=110x110&set=set1",
  },
  {
    id: "73a435e0-7c48-404d-9d24-b29c7f5a28a6",
    name: "Mayne Romayn",
    password: "b852Ds",
    email: "mromayna@furl.net",
    role: "MEMBER",
    bio: "integrate synergistic ROI",
    facebook: "http://cargocollective.com",
    instagram: "http://cisco.com",
    twitter: "https://php.net",
    linkedin: "https://wikipedia.org",
    avatar: "https://robohash.org/etdebitisdicta.png?size=110x110&set=set1",
  },
  {
    id: "b5311ae6-7f9f-4ddd-be14-3f66a9c30c56",
    name: "Maddie Oliveira",
    password: "2V9kIn",
    email: "moliveirab@tmall.com",
    role: "MEMBER",
    bio: "synergize cross-media convergence",
    avatar: "https://robohash.org/reprehenderitvoluptatemsit.png?size=110x110&set=set1",
  },
  {
    id: "0289ed68-a8db-496d-9873-dea112aea8d5",
    name: "Donnie Manlow",
    password: "rubTiW",
    email: "dmanlowc@jiathis.com",
    role: "STAFF",
    bio: "maximize turn-key initiatives",
    facebook: "http://parallels.com",
    instagram: "https://phpbb.com",
    twitter: "http://foxnews.com",
    linkedin: "http://businessinsider.com",
    avatar: "https://robohash.org/nonsaepererum.png?size=110x110&set=set1",
  },
  {
    id: "14098caf-1492-443e-9898-5238c31bf57f",
    name: "Xavier Joannic",
    password: "QaIv2F",
    email: "xjoannicd@printfriendly.com",
    role: "MEMBER",
    bio: "mesh leading-edge schemas",
    avatar: "https://robohash.org/placeatvoluptatesofficia.png?size=110x110&set=set1",
  },
  {
    id: "c0f270f3-43bd-4ed9-ad97-92ba6ce38f95",
    name: "Kare Willison",
    password: "rbv8S0",
    email: "kwillisone@miitbeian.gov.cn",
    role: "MEMBER",
    bio: "exploit dot-com users",
    avatar: "https://robohash.org/namullamiusto.png?size=110x110&set=set1",
  },
  {
    id: "6d4dfa53-5715-4648-9ff2-8882ec392806",
    name: "Bary Gleadhall",
    password: "Z4U6IGIbNLT5",
    email: "bgleadhallf@patch.com",
    role: "MEMBER",
    bio: "embrace seamless initiatives",
    facebook: "https://imdb.com",
    instagram: "http://princeton.edu",
    twitter: "http://ehow.com",
    linkedin: "https://edublogs.org",
    avatar: "https://robohash.org/commodirepudiandaedoloremque.png?size=110x110&set=set1",
  },
  {
    id: "8f324f35-c59c-45ff-8086-33a310942720",
    name: "Tabby Savaage",
    password: "H45QgZ",
    email: "tsavaageg@bbb.org",
    role: "MEMBER",
    bio: "deliver vertical portals",
    facebook: "https://blogger.com",
    instagram: "http://barnesandnoble.com",
    twitter: "https://flavors.me",
    linkedin: "https://hugedomains.com",
    avatar: "https://robohash.org/accusamusestest.png?size=110x110&set=set1",
  },
  {
    id: "c7a51eba-d554-478a-911c-05fca9ecc176",
    name: "Ollie Fishley",
    password: "MVTY7ZwFuX9",
    email: "ofishleyh@bluehost.com",
    role: "STAFF",
    bio: "integrate web-enabled action-items",
    avatar: "https://robohash.org/illumperspiciatisnostrum.png?size=110x110&set=set1",
  },
  {
    id: "5800c2c7-a0db-4cf3-987e-ae1582f19c13",
    name: "Charlean Merring",
    password: "x1I8sqy9",
    email: "cmerringi@g.co",
    role: "STAFF",
    bio: "e-enable revolutionary channels",
    avatar: "https://robohash.org/repellendussitautem.png?size=110x110&set=set1",
  },
  {
    id: "ad1d663c-0833-4f92-9b80-c027c75c8217",
    name: "Edwina Hallawell",
    password: "IAglKHO",
    email: "ehallawellj@t.co",
    role: "MEMBER",
    bio: "streamline seamless communities",
    avatar: "https://robohash.org/nonimpeditaut.png?size=110x110&set=set1",
  },
  {
    id: "522a18d7-2269-4ccf-a58d-0fa92fd2bcae",
    name: "Dickie Cornils",
    password: "wInqeBk",
    email: "dcornilsk@alexa.com",
    role: "STAFF",
    bio: "facilitate B2B paradigms",
    avatar: "https://robohash.org/sintquomolestiae.png?size=110x110&set=set1",
  },
  {
    id: "0ef6787c-b4b4-42c7-b90b-42e0c9269ca7",
    name: "Benedikta O' Meara",
    password: "nK4YYxXt7",
    email: "bol@cnbc.com",
    role: "STAFF",
    bio: "synergize mission-critical systems",
    facebook: "https://auda.org.au",
    instagram: "https://amazon.co.jp",
    twitter: "https://usgs.gov",
    linkedin: "http://mediafire.com",
    avatar: "https://robohash.org/repellatquosint.png?size=110x110&set=set1",
  },
  {
    id: "6dc12bad-c932-43b1-9da0-2f8e7ed80cf9",
    name: "Hilary Windham",
    password: "iR6adRv0",
    email: "hwindhamm@liveinternet.ru",
    role: "STAFF",
    bio: "incentivize e-business paradigms",
    avatar: "https://robohash.org/estrerumtotam.png?size=110x110&set=set1",
  },
  {
    id: "e581eefb-d07b-46cc-9326-213df66b3c0e",
    name: "Randi Muzzi",
    password: "Vay0reDFJh",
    email: "rmuzzin@sohu.com",
    role: "STAFF",
    bio: "recontextualize vertical mindshare",
    avatar: "https://robohash.org/repellatrerumculpa.png?size=110x110&set=set1",
  },
  {
    id: "f3e95f0c-5ecf-4bcd-a105-a0af12c165a7",
    name: "Ervin Routley",
    password: "4agSkx9yP0l",
    email: "eroutleyo@skyrock.com",
    role: "MEMBER",
    bio: "redefine granular e-tailers",
    facebook: "https://illinois.edu",
    instagram: "http://reverbnation.com",
    twitter: "http://blogger.com",
    linkedin: "https://noaa.gov",
    avatar: "https://robohash.org/voluptassednatus.png?size=110x110&set=set1",
  },
  {
    id: "cfd05ea3-f989-4130-904e-24065047b920",
    name: "Janean Brychan",
    password: "1R7bogE1GWES",
    email: "jbrychanp@163.com",
    role: "STAFF",
    bio: "leverage robust channels",
    avatar: "https://robohash.org/laudantiumanimiquo.png?size=110x110&set=set1",
  },
  {
    id: "7600eb16-0541-4240-97e0-1f84c6727272",
    name: "Alexi Batrim",
    password: "V04jWgXiT10",
    email: "abatrimq@mit.edu",
    role: "ADMIN",
    bio: "reinvent vertical platforms",
    avatar: "https://robohash.org/eumnoniusto.png?size=110x110&set=set1",
  },
  {
    id: "0a7cb53a-a171-4015-8067-f4b900c1e73a",
    name: "Alfi Stivers",
    password: "9Rj7he",
    email: "astiversr@state.tx.us",
    role: "STAFF",
    bio: "facilitate rich networks",
    avatar: "https://robohash.org/doloretdoloremque.png?size=110x110&set=set1",
  },
  {
    id: "a955c884-dda3-4ab7-bf81-1242fab63a10",
    name: "Jeno Swyer",
    password: "bhABJv",
    email: "jswyers@ehow.com",
    role: "MEMBER",
    bio: "whiteboard customized functionalities",
    avatar: "https://robohash.org/idlaboriosamrecusandae.png?size=110x110&set=set1",
  },
  {
    id: "56661150-d398-4f5d-9fec-2ebc76996dc7",
    name: "Mimi Kuschke",
    password: "nuxvtZXx4",
    email: "mkuschket@sfgate.com",
    role: "STAFF",
    bio: "orchestrate cross-media paradigms",
    avatar: "https://robohash.org/etvoluptatemvoluptatem.png?size=110x110&set=set1",
  },
  {
    id: "0a21bb71-7b77-4b87-b0f1-18a68407eac6",
    name: "Ernestine Lacey",
    password: "l4xGch57xf7",
    email: "elaceyu@zdnet.com",
    role: "ADMIN",
    bio: "transform rich e-business",
    avatar: "https://robohash.org/voluptatemliberoinventore.png?size=110x110&set=set1",
  },
  {
    id: "c4990608-5e56-462b-aef3-ba0d7fdf6edc",
    name: "Drud Santry",
    password: "8EZmft6VFJY",
    email: "dsantryv@gnu.org",
    role: "ADMIN",
    bio: "transition scalable functionalities",
    facebook: "http://psu.edu",
    instagram: "https://mashable.com",
    twitter: "https://wikimedia.org",
    linkedin: "https://washingtonpost.com",
    avatar: "https://robohash.org/magnamrerumofficia.png?size=110x110&set=set1",
  },
  {
    id: "b1790c0a-f9e8-4b5d-8e87-23ec3d095584",
    name: "Cleo Fullard",
    password: "SP4iRqXBZa",
    email: "cfullardw@imageshack.us",
    role: "STAFF",
    bio: "benchmark open-source relationships",
    facebook: "http://zdnet.com",
    instagram: "http://seattletimes.com",
    twitter: "http://bizjournals.com",
    linkedin: "http://godaddy.com",
    avatar: "https://robohash.org/debitisetet.png?size=110x110&set=set1",
  },
  {
    id: "6367a773-f11b-4097-9759-ccd028bfa3d8",
    name: "Grantham Robilart",
    password: "DzC6v87",
    email: "grobilartx@patch.com",
    role: "MEMBER",
    bio: "unleash web-enabled markets",
    avatar: "https://robohash.org/incidunteligendirepellendus.png?size=110x110&set=set1",
  },
  {
    id: "da4015d2-f3d1-4056-a063-35218b1bc6a7",
    name: "Enrika Rolance",
    password: "gFk4Czs",
    email: "erolancey@dropbox.com",
    role: "STAFF",
    bio: "visualize B2B e-markets",
    avatar: "https://robohash.org/quibusdamrerumvoluptatem.png?size=110x110&set=set1",
  },
  {
    id: "1fc926dd-8329-437d-b0e6-f0d81ca29949",
    name: "Jacinta Beaumont",
    password: "GdM66MLpTje",
    email: "jbeaumontz@howstuffworks.com",
    role: "STAFF",
    bio: "drive one-to-one models",
    avatar: "https://robohash.org/etnihiliusto.png?size=110x110&set=set1",
  },
  {
    id: "87c14de1-db9d-4766-89dd-bf15af12fd85",
    name: "Quincey Pedrol",
    password: "PWpIof0m9C90",
    email: "qpedrol10@nymag.com",
    role: "ADMIN",
    bio: "reinvent distributed initiatives",
    avatar: "https://robohash.org/delectusnequehic.png?size=110x110&set=set1",
  },
  {
    id: "e651b1d4-4fdd-434a-bc51-0eea139c8423",
    name: "Garvin Wilhelmy",
    password: "TRVkV1qe0bo",
    email: "gwilhelmy11@cocolog-nifty.com",
    role: "MEMBER",
    bio: "seize open-source ROI",
    avatar: "https://robohash.org/voluptatemeumvoluptates.png?size=110x110&set=set1",
  },
  {
    id: "b63a6720-5766-4585-b2b9-e74491fae8f7",
    name: "Benni Riding",
    password: "fHbBd46kV7",
    email: "briding12@hostgator.com",
    role: "MEMBER",
    bio: "empower vertical convergence",
    facebook: "http://msu.edu",
    instagram: "https://pbs.org",
    twitter: "http://army.mil",
    linkedin: "https://canalblog.com",
    avatar: "https://robohash.org/repudiandaequaeratab.png?size=110x110&set=set1",
  },
  {
    id: "d7b44f53-7566-4929-8931-05ba3b9f4ba9",
    name: "Buiron Pine",
    password: "zCWWlJj7YC",
    email: "bpine13@de.vu",
    role: "MEMBER",
    bio: "repurpose revolutionary paradigms",
    facebook: "http://yelp.com",
    instagram: "http://pcworld.com",
    twitter: "http://princeton.edu",
    linkedin: "https://angelfire.com",
    avatar: "https://robohash.org/quoquislaborum.png?size=110x110&set=set1",
  },
  {
    id: "dbd00734-ca4b-4bf8-ae2c-58af5bf2811d",
    name: "Lisette Methley",
    password: "vZ7Lkrs1l",
    email: "lmethley14@shutterfly.com",
    role: "MEMBER",
    bio: "enhance one-to-one synergies",
    facebook: "http://ft.com",
    instagram: "https://biglobe.ne.jp",
    twitter: "https://about.com",
    linkedin: "https://epa.gov",
    avatar: "https://robohash.org/perspiciatisarchitectonatus.png?size=110x110&set=set1",
  },
  {
    id: "ae583dd0-fe0b-475b-aa9a-cad2ba27b261",
    name: "Holly Dohr",
    password: "3yZUNiW1SwV",
    email: "hdohr15@nbcnews.com",
    role: "MEMBER",
    bio: "synergize ubiquitous partnerships",
    avatar: "https://robohash.org/consequuntureosofficiis.png?size=110x110&set=set1",
  },
  {
    id: "82ed474c-15e5-443b-acbe-431085e1fceb",
    name: "Elga Atthowe",
    password: "AZp5qJ8kRicF",
    email: "eatthowe16@thetimes.co.uk",
    role: "STAFF",
    bio: "orchestrate wireless e-markets",
    avatar: "https://robohash.org/ipsamvoluptatumvoluptatem.png?size=110x110&set=set1",
  },
  {
    id: "4aeeb24b-bc4d-4c67-9954-4fd341a67f06",
    name: "Nataniel Pabst",
    password: "pV57s0",
    email: "npabst17@youtube.com",
    role: "MEMBER",
    bio: "exploit clicks-and-mortar markets",
    facebook: "http://omniture.com",
    instagram: "http://feedburner.com",
    twitter: "https://utexas.edu",
    linkedin: "https://businessweek.com",
    avatar: "https://robohash.org/dignissimosrationeest.png?size=110x110&set=set1",
  },
  {
    id: "49f23e2e-d6b2-4b69-b75b-1f6e334909ac",
    name: "Darline Klimushev",
    password: "DL6a9eayzT4",
    email: "dklimushev18@salon.com",
    role: "MEMBER",
    bio: "productize efficient ROI",
    facebook: "https://networkadvertising.org",
    instagram: "http://aol.com",
    twitter: "http://nydailynews.com",
    linkedin: "https://state.gov",
    avatar: "https://robohash.org/animiquiomnis.png?size=110x110&set=set1",
  },
  {
    id: "608cf590-6277-447a-8950-5fa1f929c438",
    name: "Tome Gelland",
    password: "mIqJrGm6E",
    email: "tgelland19@desdev.cn",
    role: "STAFF",
    bio: "deploy one-to-one bandwidth",
    avatar: "https://robohash.org/deseruntquodplaceat.png?size=110x110&set=set1",
  },
  {
    id: "8f5cde87-7b55-4fbb-9c72-c996a43af914",
    name: "Nisse Pogg",
    password: "cZvWLCg6H",
    email: "npogg1a@icq.com",
    role: "MEMBER",
    bio: "strategize real-time action-items",
    avatar: "https://robohash.org/eumpossimusnobis.png?size=110x110&set=set1",
  },
  {
    id: "a8656ac1-5495-40f0-911e-4d274582a440",
    name: "Shawn Flaunier",
    password: "J4kySq",
    email: "sflaunier1b@ftc.gov",
    role: "STAFF",
    bio: "unleash extensible mindshare",
    facebook: "http://mit.edu",
    instagram: "https://nymag.com",
    twitter: "http://howstuffworks.com",
    linkedin: "http://nytimes.com",
    avatar: "https://robohash.org/minusnequeeos.png?size=110x110&set=set1",
  },
  {
    id: "42431c2e-e064-4059-8e09-5cd79172d48d",
    name: "Eugene Gent",
    password: "slnEpb",
    email: "egent1c@example.com",
    role: "STAFF",
    bio: "iterate 24/7 architectures",
    facebook: "https://ucoz.ru",
    instagram: "http://multiply.com",
    twitter: "https://issuu.com",
    linkedin: "http://technorati.com",
    avatar: "https://robohash.org/nullaaperiamquibusdam.png?size=110x110&set=set1",
  },
  {
    id: "699d7244-b0d2-4dfb-9f4e-ab35d75af136",
    name: "Liesa Campa",
    password: "PzcOwoNbhD",
    email: "lcampa1d@tinyurl.com",
    role: "MEMBER",
    bio: "utilize enterprise channels",
    avatar: "https://robohash.org/molestiasutiusto.png?size=110x110&set=set1",
  },
];
export const addDemoData = () => {
  db.users
    .bulkAdd(users)
    .then(function (lastKey) {
      console.log("Done adding 100,000 raindrops all over the place");
      console.log("Last raindrop's id was: " + lastKey); // Will be 100000.
    })
    .catch(function (e) {
      // Explicitely catching the bulkAdd() operation makes those successful
      // additions commit despite that there were errors.
      console.error(
        "Some raindrops did not succeed. However, " +
          (100000 - e.failures.length) +
          " raindrops was added successfully",
      );
    });
};
